version: "3"

services:
  namenode:
    build:
      context: "./prod-hadoop/namenode"
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - "/opt/docker/prod-hadoop:/hadoop/dfs/name:rw"
    environment:
      - CLUSTER_NAME=BigDataCluster
    env_file:
      - "./prod-hadoop/hadoop.env"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
        reservations:
          cpus: '2'
          memory: 4096M
  datanode:
    build:
      context: "./prod-hadoop/datanode"
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - "/opt/docker/prod-hadoop:/hadoop/dfs/data:rw"
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - "./prod-hadoop/hadoop.env"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
        reservations:
          cpus: '2'
          memory: 4096M

  resourcemanager:
    build:
      context: "./prod-hadoop/resourcemanager"
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - "./prod-hadoop/hadoop.env"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
        reservations:
          cpus: '2'
          memory: 4096M

  nodemanager:
    build:
      context: "./prod-hadoop/resourcemanager"
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - "./prod-hadoop/hadoop.env"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16384M
        reservations:
          cpus: '4'
          memory: 8192M
  historyserver:
    build:
      context: "./prod-hadoop/historyserver"
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - "/opt/docker/prod-hadoop:/hadoop/yarn/timeline:rw"
    env_file:
      - "./prod-hadoop/hadoop.env"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
        reservations:
          cpus: '2'
          memory: 4096M
